@startuml
[*] --> REGISTRATION_STARTED
REGISTRATION_STARTED --> REGISTRATION_NAME_PENDING
REGISTRATION_NAME_PENDING --> REGISTRATION_INTERESTS_PENDING
REGISTRATION_INTERESTS_PENDING --> REGISTRATION_LOCATION_PENDING
REGISTRATION_LOCATION_PENDING --> REGISTRATION_COMPLETED
REGISTRATION_COMPLETED --> ACTIVE

ACTIVE --> IN_MEETING
IN_MEETING --> ACTIVE
ACTIVE --> SEARCHING
SEARCHING --> IN_MEETING
SEARCHING --> ACTIVE

ACTIVE --> INACTIVE
INACTIVE --> ACTIVE

state Blocked {
    state SUSPENDED
    state BLOCKED
}

ACTIVE --> Blocked
Blocked --> ACTIVE

ACTIVE --> DELETED
DELETED --> [*]
@enduml
